version: '3.8'
services:
  spotify-tokener:
    image: ghcr.io/topi314/spotify-tokener:master
    container_name: spotify-tokener
    restart: unless-stopped
    environment:
      - SPOTIFY_TOKENER_ADDR=0.0.0.0:8080
      - SPOTIFY_TOKENER_CHROME_PATH=/usr/bin/google-chrome
      - SPOTIFY_TOKENER_LOG_LEVEL=INFO
    ports:
      - "8080:8080"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_ADMIN
