services:
  spotify-tokener:
    image: ghcr.io/topi314/spotify-tokener:master
    container_name: spotify-tokener
    restart: unless-stopped
    environment:
      - SPOTIFY_TOKENER_ADDR=0.0.0.0:8080
      - SPOTIFY_TOKENER_LOG_LEVEL=INFO
    ports:
      - "8080:8080"
